### ISSUE TITLE
Icon file-search not found

### ISSUE THREAD

**Issue by rochmadnf** [codeat3/blade-phosphor-icons#15]
![image](https://github.com/codeat3/blade-phosphor-icons/assets/53666901/3683698e-eab4-4dc5-acdc-73a362b649d0)

**Comment by swapnilsarwe** [comment]
Hey @rochmadnf ,
Can you kindly tell me which version of the package are you using ?
That will allow me to help you better.

Also try 
```
php artisan icons:cache
```

**Comment by rochmadnf** [comment]
> Hey @rochmadnf ,
> Can you kindly tell me which version of the package are you using ?
> That will allow me to help you better.
> 
> Also try 
> ```
> php artisan icons:cache
> ```

I'm using the latest version.

I have check that file in resources folder of the package and I don't found the SVG file of that file

**Comment by swapnilsarwe** [comment]
I guess you must have referred to blade-ui-kit.com to search for the icon
https://blade-ui-kit.com/blade-icons?set=36&search=search#search

The package version on the website is still 1.5.1 which maintains phosphor-icons 1.* series
you can simply downgrade the package to below version to make use of the icon.
```
        "codeat3/blade-phosphor-icons": "^1.3",
```

If you want to continue using phosphor-icons 2.* icons
you can simply use `file-magnifying-glass` instead of `file-search`.

They renamed `file-search` to `file-magnifying-glass`
Refer: https://github.com/phosphor-icons/web/releases/tag/v2.0.0 to find similar renames if you face issues with other icons.

**Comment by rochmadnf** [comment]
> I guess you must have referred to blade-ui-kit.com to search for the icon https://blade-ui-kit.com/blade-icons?set=36&search=search#search
> 
> The package version on the website is still 1.5.1 which maintains phosphor-icons 1.* series you can simply downgrade the package to below version to make use of the icon.
> 
> ```
>         "codeat3/blade-phosphor-icons": "^1.3",
> ```
> 
> If you want to continue using phosphor-icons 2.* icons you can simply use `file-magnifying-glass` instead of `file-search`.
> 
> They renamed `file-search` to `file-magnifying-glass` Refer: https://github.com/phosphor-icons/web/releases/tag/v2.0.0 to find similar renames if you face issues with other icons.

ah. ok, thanks a lot for your help.
